name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
           repository: ${{ github.repository }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: '${{ secrets.sshprivatekey }}'
          known_hosts: x
      - name: Adding Known Hosts
        run: 'ssh-keyscan -H ${{ secrets.sshhost }} >> ~/.ssh/known_hosts'
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr
          path: coding/backend
          remote_path: /var/www/html
          remote_host: '${{ secrets.sshhost }}'
          remote_user: '${{ secrets.sshuser }}'
          remote_key: '${{ secrets.sshprivatekey }}'
